const CountryData = [
  { id: 1, name: "Afghanistan", value: "Afghanistan" },
  { id: 2, name: "Albania", value: "Albania" },
  { id: 3, name: "Algeria", value: "Algeria" },
  { id: 4, name: "Andorra", value: "Andorra" },
  { id: 5, name: "Angola", value: "Angola" },
  { id: 6, name: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { id: 7, name: "Argentina", value: "Argentina" },
  { id: 8, name: "Armenia", value: "Armenia" },
  { id: 9, name: "Australia", value: "Australia" },
  { id: 10, name: "Austria", value: "Austria" },
  { id: 11, name: "Azerbaijan", value: "Azerbaijan" },
  { id: 12, name: "Bahamas", value: "Bahamas" },
  { id: 13, name: "Bahrain", value: "Bahrain" },
  { id: 14, name: "Bangladesh", value: "Bangladesh" },
  { id: 15, name: "Barbados", value: "Barbados" },
  { id: 16, name: "Belarus", value: "Belarus" },
  { id: 17, name: "Belgium", value: "Belgium" },
  { id: 18, name: "Belize", value: "Belize" },
  { id: 19, name: "Benin", value: "Benin" },
  { id: 20, name: "Bhutan", value: "Bhutan" },
  { id: 21, name: "Bolivia", value: "Bolivia" },
  { id: 22, name: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { id: 23, name: "Botswana", value: "Botswana" },
  { id: 24, name: "Brazil", value: "Brazil" },
  { id: 25, name: "Brunei", value: "Brunei" },
  { id: 26, name: "Bulgaria", value: "Bulgaria" },
  { id: 27, name: "Burkina Faso", value: "Burkina Faso" },
  { id: 28, name: "Burundi", value: "Burundi" },
  { id: 29, name: "Cabo Verde", value: "Cabo Verde" },
  { id: 30, name: "Cambodia", value: "Cambodia" },
  { id: 31, name: "Cameroon", value: "Cameroon" },
  { id: 32, name: "Canada", value: "Canada" },
  {
    id: 33,
    name: "Central African Republic",
    value: "Central African Republic",
  },
  { id: 34, name: "Chad", value: "Chad" },
  { id: 35, name: "Chile", value: "Chile" },
  { id: 36, name: "China", value: "China" },
  { id: 37, name: "Colombia", value: "Colombia" },
  { id: 38, name: "Comoros", value: "Comoros" },
  {
    id: 39,
    name: "Congo (Congo-Brazzaville)",
    value: "Congo (Congo-Brazzaville)",
  },
  { id: 40, name: "Costa Rica", value: "Costa Rica" },
  { id: 41, name: "Croatia", value: "Croatia" },
  { id: 42, name: "Cuba", value: "Cuba" },
  { id: 43, name: "Cyprus", value: "Cyprus" },
  {
    id: 44,
    name: "Czechia (Czech Republic)",
    value: "Czechia (Czech Republic)",
  },
  {
    id: 45,
    name: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  { id: 46, name: "Denmark", value: "Denmark" },
  { id: 47, name: "Djibouti", value: "Djibouti" },
  { id: 48, name: "Dominica", value: "Dominica" },
  { id: 49, name: "Dominican Republic", value: "Dominican Republic" },
  { id: 50, name: "Ecuador", value: "Ecuador" },
  { id: 51, name: "Egypt", value: "Egypt" },
  { id: 52, name: "El Salvador", value: "El Salvador" },
  { id: 53, name: "Equatorial Guinea", value: "Equatorial Guinea" },
  { id: 54, name: "Eritrea", value: "Eritrea" },
  { id: 55, name: "Estonia", value: "Estonia" },
  {
    id: 56,
    name: "Eswatini (fmr. Swaziland)",
    value: "Eswatini (fmr. Swaziland)",
  },
  { id: 57, name: "Ethiopia", value: "Ethiopia" },
  { id: 58, name: "Fiji", value: "Fiji" },
  { id: 59, name: "Finland", value: "Finland" },
  { id: 60, name: "France", value: "France" },
  { id: 61, name: "Gabon", value: "Gabon" },
  { id: 62, name: "Gambia", value: "Gambia" },
  { id: 63, name: "Georgia", value: "Georgia" },
  { id: 64, name: "Germany", value: "Germany" },
  { id: 65, name: "Ghana", value: "Ghana" },
  { id: 66, name: "Greece", value: "Greece" },
  { id: 67, name: "Grenada", value: "Grenada" },
  { id: 68, name: "Guatemala", value: "Guatemala" },
  { id: 69, name: "Guinea", value: "Guinea" },
  { id: 70, name: "Guinea-Bissau", value: "Guinea-Bissau" },
  { id: 71, name: "Guyana", value: "Guyana" },
  { id: 72, name: "Haiti", value: "Haiti" },
  { id: 73, name: "Honduras", value: "Honduras" },
  { id: 74, name: "Hungary", value: "Hungary" },
  { id: 75, name: "Iceland", value: "Iceland" },
  { id: 76, name: "India", value: "India" },
  { id: 77, name: "Indonesia", value: "Indonesia" },
  { id: 78, name: "Iran", value: "Iran" },
  { id: 79, name: "Iraq", value: "Iraq" },
  { id: 80, name: "Ireland", value: "Ireland" },
  { id: 81, name: "Israel", value: "Israel" },
  { id: 82, name: "Italy", value: "Italy" },
  { id: 83, name: "Jamaica", value: "Jamaica" },
  { id: 84, name: "Japan", value: "Japan" },
  { id: 85, name: "Jordan", value: "Jordan" },
  { id: 86, name: "Kazakhstan", value: "Kazakhstan" },
  { id: 87, name: "Kenya", value: "Kenya" },
  { id: 88, name: "Kiribati", value: "Kiribati" },
  { id: 89, name: "Kuwait", value: "Kuwait" },
  { id: 90, name: "Kyrgyzstan", value: "Kyrgyzstan" },
  { id: 91, name: "Laos", value: "Laos" },
  { id: 92, name: "Latvia", value: "Latvia" },
  { id: 93, name: "Lebanon", value: "Lebanon" },
  { id: 94, name: "Lesotho", value: "Lesotho" },
  { id: 95, name: "Liberia", value: "Liberia" },
  { id: 96, name: "Libya", value: "Libya" },
  { id: 97, name: "Liechtenstein", value: "Liechtenstein" },
  { id: 98, name: "Lithuania", value: "Lithuania" },
  { id: 99, name: "Luxembourg", value: "Luxembourg" },
  { id: 100, name: "Madagascar", value: "Madagascar" },
  { id: 101, name: "Malawi", value: "Malawi" },
  { id: 102, name: "Malaysia", value: "Malaysia" },
  { id: 103, name: "Maldives", value: "Maldives" },
  { id: 104, name: "Mali", value: "Mali" },
  { id: 105, name: "Malta", value: "Malta" },
  { id: 106, name: "Marshall Islands", value: "Marshall Islands" },
  { id: 107, name: "Mauritania", value: "Mauritania" },
  { id: 108, name: "Mauritius", value: "Mauritius" },
  { id: 109, name: "Mexico", value: "Mexico" },
  { id: 110, name: "Micronesia", value: "Micronesia" },
  { id: 111, name: "Moldova", value: "Moldova" },
  { id: 112, name: "Monaco", value: "Monaco" },
  { id: 113, name: "Mongolia", value: "Mongolia" },
  { id: 114, name: "Montenegro", value: "Montenegro" },
  { id: 115, name: "Morocco", value: "Morocco" },
  { id: 116, name: "Mozambique", value: "Mozambique" },
  {
    id: 117,
    name: "Myanmar (formerly Burma)",
    value: "Myanmar (formerly Burma)",
  },
  { id: 118, name: "Namibia", value: "Namibia" },
  { id: 119, name: "Nauru", value: "Nauru" },
  { id: 120, name: "Nepal", value: "Nepal" },
  { id: 121, name: "Netherlands", value: "Netherlands" },
  { id: 122, name: "New Zealand", value: "New Zealand" },
  { id: 123, name: "Nicaragua", value: "Nicaragua" },
  { id: 124, name: "Niger", value: "Niger" },
  { id: 125, name: "Nigeria", value: "Nigeria" },
  { id: 126, name: "North Korea", value: "North Korea" },
  { id: 127, name: "North Macedonia", value: "North Macedonia" },
  { id: 128, name: "Norway", value: "Norway" },
  { id: 129, name: "Oman", value: "Oman" },
  { id: 130, name: "Pakistan", value: "Pakistan" },
  { id: 131, name: "Palau", value: "Palau" },
  { id: 132, name: "Palestine State", value: "Palestine State" },
  { id: 133, name: "Panama", value: "Panama" },
  { id: 134, name: "Papua New Guinea", value: "Papua New Guinea" },
  { id: 135, name: "Paraguay", value: "Paraguay" },
  { id: 136, name: "Peru", value: "Peru" },
  { id: 137, name: "Philippines", value: "Philippines" },
  { id: 138, name: "Poland", value: "Poland" },
  { id: 139, name: "Portugal", value: "Portugal" },
  { id: 140, name: "Qatar", value: "Qatar" },
  { id: 141, name: "Romania", value: "Romania" },
  { id: 142, name: "Russia", value: "Russia" },
  { id: 143, name: "Rwanda", value: "Rwanda" },
  { id: 144, name: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { id: 145, name: "Saint Lucia", value: "Saint Lucia" },
  {
    id: 146,
    name: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { id: 147, name: "Samoa", value: "Samoa" },
  { id: 148, name: "San Marino", value: "San Marino" },
  { id: 149, name: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { id: 150, name: "Saudi Arabia", value: "Saudi Arabia" },
  { id: 151, name: "Senegal", value: "Senegal" },
  { id: 152, name: "Serbia", value: "Serbia" },
  { id: 153, name: "Seychelles", value: "Seychelles" },
  { id: 154, name: "Sierra Leone", value: "Sierra Leone" },
  { id: 155, name: "Singapore", value: "Singapore" },
  { id: 156, name: "Slovakia", value: "Slovakia" },
  { id: 157, name: "Slovenia", value: "Slovenia" },
  { id: 158, name: "Solomon Islands", value: "Solomon Islands" },
  { id: 159, name: "Somalia", value: "Somalia" },
  { id: 160, name: "South Africa", value: "South Africa" },
  { id: 161, name: "South Korea", value: "South Korea" },
  { id: 162, name: "South Sudan", value: "South Sudan" },
  { id: 163, name: "Spain", value: "Spain" },
  { id: 164, name: "Sri Lanka", value: "Sri Lanka" },
  { id: 165, name: "Sudan", value: "Sudan" },
  { id: 166, name: "Suriname", value: "Suriname" },
  { id: 167, name: "Sweden", value: "Sweden" },
  { id: 168, name: "Switzerland", value: "Switzerland" },
  { id: 169, name: "Syria", value: "Syria" },
  { id: 170, name: "Tajikistan", value: "Tajikistan" },
  { id: 171, name: "Tanzania", value: "Tanzania" },
  { id: 172, name: "Thailand", value: "Thailand" },
  { id: 173, name: "Timor-Leste", value: "Timor-Leste" },
  { id: 174, name: "Togo", value: "Togo" },
  { id: 175, name: "Tonga", value: "Tonga" },
  { id: 176, name: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { id: 177, name: "Tunisia", value: "Tunisia" },
  { id: 178, name: "Turkey", value: "Turkey" },
  { id: 179, name: "Turkmenistan", value: "Turkmenistan" },
  { id: 180, name: "Tuvalu", value: "Tuvalu" },
  { id: 181, name: "Uganda", value: "Uganda" },
  { id: 182, name: "Ukraine", value: "Ukraine" },
  { id: 183, name: "United Arab Emirates", value: "United Arab Emirates" },
  { id: 184, name: "United Kingdom", value: "United Kingdom" },
  {
    id: 185,
    name: "United States of America",
    value: "United States of America",
  },
  { id: 186, name: "Uruguay", value: "Uruguay" },
  { id: 187, name: "Uzbekistan", value: "Uzbekistan" },
  { id: 188, name: "Vanuatu", value: "Vanuatu" },
  { id: 189, name: "Venezuela", value: "Venezuela" },
  { id: 190, name: "Vietnam", value: "Vietnam" },
  { id: 191, name: "Yemen", value: "Yemen" },
  { id: 192, name: "Zambia", value: "Zambia" },
  { id: 193, name: "Zimbabwe", value: "Zimbabwe" },
];

export default CountryData;
